on: push
name: Publish Website Dry Run
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3

    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: 170.187.192.100
        remote-user: root
        private-ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
        ssh-port: 22
        destination-path: ~/web/
        rsync-options: --dry-run --archive --verbose --compress --human-readable --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore
