on: push
name: Publish Website
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3

    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ssh.econrad.me
        remote-user: admin
        private-ssh-key: ${{ secrets.PRIVATE_SSH_KEY_2 }}
        ssh-port: 2222
        destination-path: ~/Sites/econrad
        rsync-options: --archive --verbose --compress --human-readable --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore
